#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os.path

VariantDir("build", "src", duplicate=False)

Import("env")
env = env.Clone()

env.AppendUnique(
	CPPPATH=[os.path.join("#core", "include"), "include"],
	LIBPATH=[os.path.join("#core", "lib")],
	CFLAGS=["-std=c99"],
	LINKFLAGS=["-Wl,-rpath,core/lib"],
	LIBS=["core", "glut"],
)

targets = [env.Program(os.path.join("bin", "test"),
				[os.path.join("build", node.name)
		 			for node in env.Glob(os.path.join("src", "*.c"))])]

Return("targets")
