#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os.path

import ceutils

VariantDir("build", "src", duplicate=False)

Import("env")
env = env.Clone()

env.AppendUnique(
	CPPPATH=["include"],
)

sources = ceutils.filter_sources(env, env.Glob(os.path.join("src", "*.c")))

targets = [builder(os.path.join("lib", "game"), [os.path.join("build", node.name)
	for node in sources]) for builder in (env.StaticLibrary, env.SharedLibrary)]

Return("targets")
