#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os.path

VariantDir("build", "src", duplicate=False)

Import("env")
env = env.Clone()

env.AppendUnique(
	CPPPATH=["include"],
)

targets = [builder(os.path.join("lib", "game"),
					[os.path.join("build", node.name)
						for node in env.Glob(os.path.join("src", "*.c"))])
			for builder in (env.StaticLibrary, env.SharedLibrary)]

Return("targets")
