# -*- coding: utf-8 -*-

# This file is part of Open Evil Islands.
#
# Open Evil Islands is an open source, cross-platform port of the original Evil Islands from Nival.
# Copyright (C) 2009-2016 Yanis Kurganov <yanis.kurganov@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import os

import SCons

import utils

Import("env")

env = env.Clone(
    tools=["rc"],
    RCROOTPATH="res",
    RCBUILDPATH="build",
    RCBUILDOBJPATH=os.path.join("build", "$GEN_PATH"),
)

env.PrependUnique(
    CPPPATH=["include"],
)

env.VariantDir(os.path.join("build", "$GEN_PATH"), "src", duplicate=False)

sources = [os.path.join("build", "$GEN_PATH", node.name) for node in
    utils.filter_sources(env, env.Glob(os.path.join("src", "*.cpp")))] + \
    env.Glob(os.path.join("res", "resource.cerc"))

lib = env.Library(os.path.join("lib", "$GEN_PATH", "engine"), sources)

targets = [env.Command(os.path.join("lib", SCons.Util.adjustixes("engine",
    env.subst("$LIBPREFIX"), env.subst("$LIBSUFFIX"))), lib,
    Copy("$TARGET", "$SOURCE"))]

Return("targets")
