# -*- coding: utf-8 -*-

# This file is part of Open Evil Islands.
#
# Open Evil Islands is an open source, cross-platform port of the original Evil Islands from Nival.
# Copyright (C) 2009-2016 Yanis Kurganov <yanis.kurganov@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import utils
import os

Import("env")

env = env.Clone(
    tools=["res"],
    RES_OBJECT_BUILD_PATH="$ENGINE_OBJECT_BUILD_PATH",
    ENGINE_OBJECT_BUILD_PATH=os.path.join("$ESCONS_OBJECT_BUILD_PATH", "engine"),
)

env.VariantDir("$ENGINE_OBJECT_BUILD_PATH", "sources", duplicate=False)

sources = [os.path.join("$ENGINE_OBJECT_BUILD_PATH", node.name) for node in utils.filter_sources(env, env.Glob(os.path.join("sources", "*.cpp")))]
resources = [os.path.join("resources", "resource.res")]

targets = [env.Library(os.path.join("$ESCONS_LIBRARY_BUILD_PATH", "engine"), sources + resources)]

Return("targets")
