#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  This file is part of Cursed Earth.
#
#  Cursed Earth is an open source, cross-platform port of Evil Islands.
#  Copyright (C) 2009-2010 Yanis Kurganov.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

import os.path

import SCons.Util

import ceutils

Import("env")
env = env.Clone(
	tools=["ceglsl"],
	GLSL_BUILDPATH=os.path.join("build"),
)

env.AppendUnique(
	CPPPATH=["include", os.path.join("build", "include")],
)

env.VariantDir(os.path.join("build", "$GEN_PATH"), "src", duplicate=False)

c = ceutils.filter_sources(env, env.Glob(os.path.join("src", "*.c")))
vert = env.Glob(os.path.join("src", "*.vert"))
frag = env.Glob(os.path.join("src", "*.frag"))
glsl = env.Glob(os.path.join("src", "ceshaderdata.glsl"))

sources = [os.path.join("build", "$GEN_PATH", node.name)
			for node in c + vert + frag + glsl]

lib = env.Library(os.path.join("lib", "$GEN_PATH", "engine"), sources)

targets = [env.Command(os.path.join("lib", SCons.Util.adjustixes("engine",
	env.subst("$LIBPREFIX"), env.subst("$LIBSUFFIX"))), lib,
	Copy("$TARGET", "$SOURCE"))]

Return("targets")
