#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

VariantDir("build", "src", duplicate=False)

Import("env")
env = env.Clone()

env.AppendUnique(
	CPPPATH=[os.path.join("#game", "include")],
	LIBPATH=[os.path.join("#game", "lib")],
	LINKFLAGS=["-Wl,-rpath,game/lib"],
	LIBS=["game", "glut"],
)

targets = []

for name in os.listdir("."):
	if os.path.isdir(name):
		VariantDir(os.path.join(name, "build"),
			os.path.join(name, "src"), duplicate=False)
		targets.append(env.Alias(name, env.Program(os.path.join(
			name, "bin", name), [os.path.join(name, "build", node.name)
			for node in env.Glob(os.path.join(name, "src", "*.c"))])))

Return("targets")
