#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  This file is part of Cursed Earth.
#
#  Cursed Earth is an open source, cross-platform port of Evil Islands.
#  Copyright (C) 2009-2015 Yanis Kurganov <ykurganov@users.sourceforge.net>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

import os

import SCons

import utils

Import("env")

env.PrependUnique(
    CPPPATH=["include", "native",
    os.path.join("#engine", "include"),
    os.path.join("#script", "include")]
)

env.VariantDir(os.path.join("build", "$GEN_PATH"), "src", duplicate=False)

sources = [os.path.join("build", "$GEN_PATH", node.name) for node in
    utils.filter_sources(env, env.Glob(os.path.join("src", "*.cpp")))]

lib = env.Library(os.path.join("lib", "$GEN_PATH", "ai"), sources) # does this need to be a library?
# I mostly wanted to separate my code from the rest of the engine, because I find include and sources dirs
# with 30+ files unmanageable and hard to understand and keep track of

targets = [env.Command(os.path.join("lib", SCons.Util.adjustixes("ai",
    env.subst("$LIBPREFIX"), env.subst("$LIBSUFFIX"))), lib,
    Copy("$TARGET", "$SOURCE"))]

Return("targets")
