# -*- coding: utf-8 -*-

# This file is part of Open Evil Islands.
#
# Open Evil Islands is an open source, cross-platform port of the original Evil Islands from Nival.
# Copyright (C) 2009-2016 Yanis Kurganov <yanis.kurganov@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import os

Import("env")

env = env.Clone(
    tools=["qt"],
    RESFILEVIEWER_OBJECT_BUILD_PATH=os.path.join("$ESCONS_OBJECT_BUILD_PATH", "resfileviewer"),
)

env.VariantDir("$RESFILEVIEWER_OBJECT_BUILD_PATH", "sources", duplicate=False)

sources = [os.path.join("$RESFILEVIEWER_OBJECT_BUILD_PATH", node.name) for node in env.Glob(os.path.join("sources", "*.cpp"))]
forms = env.Glob(os.path.join("forms", "*.ui"))

targets = [
    env.Program(
        os.path.join("$ESCONS_BINARY_BUILD_PATH", "resfileviewer"),
        sources + forms
    )
]

Return("targets")
